In [ ]:
import numpy as np
import pandas as pd
from sklearn.metrics import accuracy_score, mean_squared_error
import matplotlib.pyplot as plt
from tqdm import tqdm_notebook

# Sigmoid Neuron using Squared Error Loss (S.E.L)

In [605]:
class SigmoidNeuron:
    def __init__(self):
        self.w=None
        self.b=None
        
    def perceptron(self,x):
        return np.dot(x,self.w.T)+self.b
    
    def sigmoid(self,x):
        return 1.0/(1.0+np.exp(-x))
    
    def grad_w(self,x,y):
        y_pred=self.sigmoid(self.perceptron(x))
        return (y_pred-y)*y_pred*(1-y_pred)*x
    
    def grad_b(self,x,y):
        y_pred=self.sigmoid(self.perceptron(x))
        return (y_pred-y)*y_pred*(1-y_pred)
    
    def fit(self, X,Y,epoch,learning_rate=1,initialize=True,display_loss=True):
        #initialize w,b
        if initialize:
            self.w=np.random.randn(1, X.shape[1])
            self.b=0
        if display_loss:
            loss=[]
        for i in tqdm_notebook(range(epoch),total=epoch,unit='epoch'):
            dw=0
            db=0
            for x,y in zip(X,Y):
                dw+=self.grad_w(x,y)
                db+=self.grad_b(x,y)
            self.w-=learning_rate*dw
            self.b-=learning_rate*db
            
            if display_loss:
                Y_pred=self.sigmoid(self.perceptron(x))
                loss.append(mean_squared_error(Y_pred,y))
        
        if display_loss:
      
            plt.plot(loss)
            
            plt.xlabel('Epochs')
            plt.ylabel('Mean Squared Error')
            plt.show()
            
    def predict(self,X):
        Y_pred=[]
        for x in X:
            y_pred=self.sigmoid(self.perceptron(x))
            Y_pred.append(y_pred)
        return np.asarray(Y_pred)
        


# Fit for Toy Data

In [606]:
X=np.random.randn(3,2)

In [607]:
X

array([[ 0.34422553,  1.24224186],
       [ 0.95759031, -0.05904354],
       [ 1.16049337,  0.26562873]])

In [608]:
Y=[0,1,1]

In [609]:
sn=SigmoidNeuron()

In [610]:
sn.fit(X,Y,1,0.25,True)

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:27: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`


TypeError: Expected sequence or array-like, got <class 'int'>

In [611]:
sn.w

array([[0.19864035, 0.85598274]])

In [612]:
sn.b

array([0.01893504])

In [613]:
for i in range(10):
    print(sn.w,sn.b)                                                   
    sn.fit(X,Y,1,0.25,False)                                            #We are not initialising a new w,b everytime 
                                                                        # You can see w is decreasing slowly and b is also decreasing

[[0.19864035 0.85598274]] [0.01893504]


C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:27: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`


TypeError: Expected sequence or array-like, got <class 'int'>

In [614]:
for i in range(10):
    print(sn.w,sn.b)                                                   
    sn.fit(X,Y,1,1,False)                                            #We are not initialising a new w,b everytime 
                                                                        # You can see w is decreasing slowly and b is also decreasing

[[0.24034631 0.81722907]] [0.0354829]




C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:27: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`


TypeError: Expected sequence or array-like, got <class 'int'>

# Applying Sigmoid Neuron Model for Mobile Phone Like/Dislike Prediction:

In [ ]:
data=pd.read_csv('mobilephone_cleaned.csv')
data.shape
data

In [615]:
#Seperating the input and the output 
X=data.drop('Rating',axis=1)
Y=data['Rating']

In [616]:
#Converting Y from dataframes to numpy values
Y=Y.values

In [617]:
threshold=4.2

In [ ]:
data['Class']=(data['Rating']>=threshold).astype(np.int)

In [ ]:
data

In [ ]:
data['Class']

In [ ]:
data['Class'].value_counts()                         # The data set has phones more likely to be bought

In [ ]:
data['Class'].value_counts(normalize=True)    

In [ ]:
Y_binarised=data['Class'].values

# Standardization (Only Concept Demo)

In [ ]:
import  matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler

In [ ]:
R=np.random.random([100,1])

In [ ]:
plt.plot(R)

In [ ]:
np.mean(R)

In [ ]:
np.std(R)

For standardization, import an instance of StandardScaler()

After standardising, the resultant data has mean=0 and standard deviation=1


In [ ]:
scaler=StandardScaler()

In [ ]:
scaler.fit(R)

In [ ]:
scaler.mean_

In [ ]:
R_transformed=scaler.transform(R)

In [ ]:
np.mean(R_transformed)

In [ ]:
np.std(R_transformed)

In [ ]:
plt.plot(R_transformed)

# Applying Standardization to our data

We need to standardise our data seperately as train and test data 

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
X_train,X_test,Y_train,Y_test=train_test_split(X,Y, random_state=0,stratify=Y_binarised)

In [ ]:
X_train.shape

In [ ]:
Y_train.shape

In [ ]:
X_test.shape

In [ ]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()

In [ ]:
X_train_scaled=scaler.fit(X_train)


In [ ]:
X_train_scaled=scaler.transform(X_train)

In [ ]:
X_test_scaled=scaler.transform(X_test)

In [ ]:
minmax_scaler=MinMaxScaler()

In [ ]:
minmax_scaler=minmax_scaler.fit_transform(Y_train)

In [ ]:
Y_scaled_train=minmax_scaler.fit_transform(Y_train.reshape(-1,1))

In [ ]:
Y_scaled_test=minmax_scaler.transform(Y_test.reshape(-1,1))

In [ ]:
threshold=np.asarray(threshold)

In [ ]:
scaled_threshold=minmax_scaler.transform(threshold.reshape(-1,1))          
# Our threshold must also change with the standardization !
#Initial threshold was 4.2/5  but now the standardized equivalent will be 0.68/5

In [ ]:
scaled_threshold [0][0]                                         

In [ ]:
Y_binarised_train=(Y_scaled_train>scaled_threshold).astype('int').ravel()
Y_binarised_test=(Y_scaled_test>scaled_threshold).astype('int').ravel()

# ravel() is used to flatten the array

In [ ]:
Y_binarised_train

In [ ]:
sn=SigmoidNeuron()

In [ ]:
sn.fit(X_train_scaled,Y_scaled_train,epoch=5000,learning_rate=0.01)

In [ ]:
Y_pred_train=sn.predict(X_train_scaled)
Y_pred_test=sn.predict(X_test_scaled)

In [ ]:
Y_pred_binarised_train=(Y_pred_train>scaled_threshold).astype('int').ravel()
Y_pred_binarised_test=(Y_pred_test>scaled_threshold).astype('int').ravel()

In [ ]:
Y_pred_binarised_train

In [ ]:
from sklearn.metrics import accuracy_score

In [ ]:
accuracy_train=accuracy_score(Y_pred_binarised_train,Y_binarised_train)
accuracy_train

In [ ]:
accuracy_test=accuracy_score(Y_pred_binarised_test,Y_binarised_test)
accuracy_test

# Sigmoid Neuron using crossentropy loss function (C.E.L) 

In [ ]:
import numpy as np
import pandas as pd
from sklearn.metrics import accuracy_score, mean_squared_error
import matplotlib.pyplot as plt
from tqdm import tqdm_notebook
from sklearn.metrics import accuracy_score

In [ ]:
class SigmoidNeuronCEL:
    def __init__(self):
        self.w=None
        self.b=None
        
    def perceptron(self,x):
        return np.dot(x,self.w.T)+self.b
    
    def sigmoid(self,x):
        return 1.0/(1.0+np.exp(-(x)))
    
    def grad_w(self,x,y):                            #Gradient of W has been calaculated by following the Cross entropy Loss minimization technique
        y_pred=self.sigmoid(self.perceptron(x))
        return (y_pred-y)*x

    def grad_b(self,x,y):                            #Gradient of b has been calaculated by following the Cross entropy Loss minimization technique
        y_pred=self.sigmoid(self.perceptron(x))
        return (y_pred-y)

    def fit(self, X,Y,epoch,learning_rate=1,initialize=True,display_loss=True):
        #initialize w,b
        if initialize:
            self.w=np.random.randn(1, X.shape[1])
            self.b=0
        if display_loss:
            loss=[]
        for i in tqdm_notebook(range(epoch),total=epoch,unit='epoch'):
            dw=0
            db=0
            for x,y in zip(X,Y):
                dw+=self.grad_w(x,y)
                db+=self.grad_b(x,y)
            self.w-=learning_rate*dw
            self.b-=learning_rate*db
            
          # For Plotting the Loss graph
            if display_loss:
                    Y_pred=self.sigmoid(self.perceptron(x))
                    loss.append(mean_squared_error(Y_pred,y))
      
        if display_loss:

            plt.plot(loss)

            plt.xlabel('Epochs')
            plt.ylabel('Mean Squared Error')
            plt.show()
            
    def error(self,X,Y):
        err=0.0
        for x,y in zip(X,Y):
            y_pred=self.sigmoid(self.perceptron(x))
            err+=-[  (1-y)*math.log(1-y_pred,2)  +   y*math.log(y_pred,2) ]
        return err
   
    def predict(self,X):
        Y_pred=[]
        for x in X:
            y_pred=self.sigmoid(self.perceptron(x))
            Y_pred.append(y_pred)
        return np.asarray(Y_pred)
        
            

In [ ]:
sn=SigmoidNeuronCEL()

In [ ]:
sn.fit(X_train_scaled,Y_scaled_train,epoch=5000,learning_rate=0.01)

In [ ]:
# Computing the accuracy !
Y_pred_train=sn.predict(X_train_scaled)
Y_pred_test=sn.predict(X_test_scaled)


In [ ]:
Y_pred_binarised_train=(Y_pred_train>scaled_threshold).astype('int').ravel()
Y_pred_binarised_test=(Y_pred_test>scaled_threshold).astype('int').ravel()

In [ ]:
Y_pred_binarised_train

In [ ]:
accuracy_train=accuracy_score(Y_pred_binarised_train,Y_binarised_train)
accuracy_train

In [ ]:
accuracy_test=accuracy_score(Y_pred_binarised_test,Y_binarised_test)
accuracy_test